tiiuae/ghaf-fmo-laptop

flake.lock
modules/flake-module.nix
modules/microvm/docker/config.nix
modules/microvm/docker/vm.nix
modules/microvm/host.nix
profile/fmo.nix

Enable givc system agent instead of the default user session agent.

Enable givc system agent

---

flake.lock
flake.nix

Remove givc input pin

---

flake.lock
flake.nix
overlays/custom-packages/default.nix
overlays/custom-packages/lisgd/config.h
overlays/custom-packages/lisgd/default.nix
overlays/flake-module.nix
targets/flake-module.nix

Including the overlay
And the upstream packages

pkgs: Add the packages that we depend on

---

flake.lock
modules/microvm/docker/vm.nix
modules/microvm/guivm.nix
profile/fmo.nix

Use the latest modules and refactor the inclusion of the new app vm mechanism.

bump: Take in the latest changes in Ghaf

---

.github/workflows/check.yml

- Start using `pull_request_target` trigger to be able to use secrets required to access the private repo dependency in the pull request event. The setup is similar to how this works in [Ghaf](https://github.com/tiiuae/ghaf), and is fully explained in: https://confluence.tii.ae/pages/viewpage.action?pageId=43354245
- Start using `webfactory/ssh-agent` to allow pulling the flake input dependency from the private repo
- Adds authentication steps to the workflow now that we are dealing with secrets
- Update all github action dependencies

Add authorization step to check workflow

---

.github/workflows/check.yml

- Start using nix remote builders, instead of running the checks on github hosted runners
- Remove maximizing github runner rootfs space: builds are no longer run on the github hosted
runners, so there's no need to maximize the build space.
Notice: the failure in [no-workflow-changes](https://github.com/tiiuae/ghaf-fmo-laptop/actions/runs/13946962148/job/39036328058#step:4:13) is intentional: it's intended to warn that the workflow changes introduced in this PR will only take impact after merge. In other words, the check results summarized in this PR still use the old version of workflows not including these changes, making the results meaningless for this PR.

Use nix remote builder

---

.gitignore
nix/checks.nix
nix/devshell.nix

fix: pre-commit issue

---

flake.nix
modules/flake-module.nix
modules/fmo/dci-service/default.nix
modules/fmo/fmo-nats-server/default.nix
modules/fmo/registration-agent-laptop/default.nix
modules/microvm/docker/config.nix
modules/microvm/docker/vm.nix
modules/microvm/host.nix
modules/microvm/msg/config.nix
modules/microvm/msg/vm.nix
packages/flake-module.nix
packages/fmo-registration/default.nix
profile/fmo.nix
targets/flake-module.nix

- Adds first working prototype for the laptop registration
- TOODs indicate further work, also msg-vm should probably be removed
- Dell laptop has performance issues due to the amount of VMs and allocated memory
- lots of hardcoding to get things running
- Notes on some missing features:
- dynamic hostname (mDNS)
- IP updates and networkmanager profiles

WIP - first working registration prototype

---

.github/workflows/check.yml
modules/fmo/fmo-nats-server/default.nix

1. Checkout the pull request head, not the base
2. Rebase the PR changes on top of the target branch before running the checks
3. Fix reuse lint for `fmo-nats-server/default.nix` : this got merged from https://github.com/tiiuae/ghaf-fmo-laptop/pull/14, due to the fact that the check did not run against the correct changes, see: bullet point (1)
Checks will fail for this PR, but will pass as soon as this is merged.

Rebase changes before running checks

---

README.md
flake.lock
modules/hardware/definition/dell-latitude-7230.nix
modules/hardware/flake-module.nix
modules/hardware/resources/dell-latitude-7330.nix
modules/hardware/resources/lenovo-x1-carbon-gen11.nix
packages/fmo-build-helper/default.nix
targets/flake-module.nix
targets/mkInstaller.nix
targets/mkLaptopConfiguration.nix

Add the resource allocation files.

hw: add 7330 and x1-gen11

---

flake.lock
modules/profile/flake-module.nix
modules/profile/fmo.nix
modules/profile/personalize.nix
targets/flake-module.nix

Add setup to add fmo specific ssh authorized keys for development.

Add fmo development ssh key setup

---

flake.lock
modules/hardware/definition/external-usb.nix
modules/hardware/flake-module.nix
modules/hardware/resources/alienware-m18-r2.nix
modules/hardware/resources/demo-tower-mk1.nix
targets/flake-module.nix

Add demo tower

---

modules/flake-module.nix
modules/microvm/guivm.nix
modules/profile/fmo.nix

enable rendering in gui and add the libaom AV1 decoder.

chrome: in the guivm with nvidia render

---

modules/fmo/fmo-docker-networking/default.nix
modules/microvm/docker/config.nix

Add docker-vm nat to translate docker bridge network to internal interface.

Add docker-vm nat

---

modules/profile/personalize.nix

Add toros pub key to personalize.nix

---

flake.lock
flake.nix

the biggest change is in the version on the nixpkgs

bump: bump the flake lock especially nixpkgs

---

flake.lock

bump ghaf deps to get the latest vulkan code.

bump: get the latest vulkan changes

---

README.md
REUSE.toml
justfile
nix/devshell.nix

Add documentation for GitHub PAT setup to access private repositories. Introduce justfile for simplified command handling. Improve commands in README to use just wrappers. Update fmo-build-helper usage example.

feat(dev): add github token setup instructions and just commands

---

.github/workflows/check.yml
flake.lock
flake.nix
justfile
modules/fmo/flake-module.nix
modules/fmo/fmo-update-hostname/default.nix
modules/fmo/onboarding-agent/default.nix
modules/microvm/docker/config.nix
modules/microvm/docker/vm.nix
nix/devshell.nix
packages/flake-module.nix
packages/fmo-onboarding/default.nix
packages/fmo-registration/default.nix

Integrate changes from https://github.com/tiiuae/ghaf-fmo-laptop/pull/26, fixing the github action check workflow.
The  [onboarding-agent](https://github.com/tiiuae/onboarding-agent) requires access to various private go repositories when building the go package. This PR includes the required changes to the github action check workflow to allow building the onboarding-agent:
- Use temporary token generated with create-github-app-token to access the private onboarding-agent go dependencies
- Mount the temporary token to nix sandbox on remote-builder using the `extra-sandbox-paths`, this requires an update to onboarding-agent to include the changes from https://github.com/tiiuae/onboarding-agent/pull/27
- Use a deployment key to access the …

Build onboarding-agent in github action

---

modules/hardware/resources/alienware-m18-r2.nix

Add more RAM and vCPUs to gui-vm to handle bigger workloads.
Add more RAM and vCPUs to gui-vm to handle bigger workloads in GPU accelerated browsers.

Add more resources to guivm

---

modules/microvm/guivm.nix

Enable audio for gui-vm applications such as firefox and chrome.
Enable audio for gui-vm applications such as firefox and chrome.

Audio for gui-vm apps

---

.envrc
.gitignore
CONTRIBUTING.md
modules/fmo/fmo-onboarding-agent/default.nix
modules/fmo/fmo-update-hostname/default.nix
modules/microvm/docker/config.nix
modules/microvm/docker/vm.nix
nix/checks.nix
overlays/custom-packages/default.nix
packages/flake-module.nix
packages/fmo-offboarding/default.nix
packages/fmo-onboarding/default.nix
targets/mkInstaller.nix

Add feature to allow deletion of FMO provisioning data. This allows for the device to be re-provisioned multiple times.
Others:
- fix eval warning
- update license headers

Offboarding functionality

---

modules/hardware/resources/demo-tower-mk1.nix

Increase the assignment to the gui-vm to support more streams.

resources: Adjust memory and cpu assignment

---

modules/microvm/guivm.nix
modules/profile/fmo.nix

Enable nvidia drivers only if nvidia gpu device is present in hardware config.
1. Check target configs with `nix repl`
2. Build nvidia/non-nvidia targets

Enable nvidia drivers based on device list

---

flake.lock
flake.nix
modules/hardware/resources/lenovo-x1-carbon-gen11.nix
modules/microvm/guivm.nix
modules/microvm/host.nix

latest nixpkgs and the touch enabled gui-vm.
1. ...

bump: nixpkgs and the dp-usb

---

modules/profile/personalize.nix

SSH keys added for the integration team
1. ...

SSH keys added for the integration team

---

flake.lock

Update to onboarding agent 0.0.7
https://github.com/tiiuae/onboarding-agent/releases/tag/v0.0.7
1. ...

bump: Get the latest onboarding agent

---

packages/fmo-onboarding/default.nix

Preventing people from using emtpy hostname in onboarding.
1. ...

fix(hostname): Emtpy input

---

flake.lock
modules/microvm/guivm.nix

Add some more defaults to enable more offload to the GPU for video rendering.
1. ...

firefox: set some defaults for the video hw

---

modules/profile/personalize.nix

add keys to personalize

---

flake.lock

Update onboarding agent version. Onboarding agent now supports RSA key algorithm and PKCS#1 key format via flags or configuration. More in the onboading-agent [README.md](https://github.com/tiiuae/onboarding-agent/?tab=readme-ov-file#provisioning).
1. Install as usual
2. If swarm-server shows error logs related to parsing the key format, change the configuration, as described in the onboarding-agent README.md

modules(onboarding): update version

---

modules/microvm/host.nix

Add icon/entry for the display management application.
1. ...

Add desktop entry for display app

---

flake.lock

some improvements for intel gpu only mode
1. ...

bump: take the latest ghaf

---

modules/hardware/resources/alienware-m18-r2.nix
modules/hardware/resources/lenovo-x1-carbon-gen11.nix
modules/profile/fmo.nix

allocate some more resources to the gui-vm
1. ...

vms: disable chrome and zathura

---

.github/workflows/authorize.yml
.github/workflows/check.yml
.github/workflows/warn-on-workflow-changes.yml

- Authorize pre-merge workflow runs based on author's membership in tiiuae organization, separating the `authorization.yml` to its own workflow.
- Move the workflow changed warning to `warn-on-workflow-changes.yml` which can trigger on `pull_request` rather than `pull_request_target`. 
1. ...

GhA: Simplify authorization

---

flake.lock
modules/microvm/netvm.nix

Update to the latest ghaf and associated packages.
1. ...

bump: Get the latest inputs

---

flake.lock

bump: latest onboarding agent and ghaf

---

flake.lock
modules/microvm/guivm.nix

supposedly this improves wayland gpu rendering on nvidia.
1. ...

bump: chrome, firefox, gpu updates

---

modules/microvm/guivm.nix

add wl-screenrec to guivm

---

flake.lock
flake.nix
modules/hardware/flake-module.nix
modules/hardware/resources/tower-5080.nix
modules/profile/fmo.nix
targets/flake-module.nix

Add new demo tower hardware and target.
1. ...

feat(hardware): add new demo tower

---

modules/microvm/guivm.nix

1. **Add [resources](https://github.com/nokyan/resources) app:**
- Allows monitoring system resources and processes.
- Displays GPU encode/decode usage
- Works more consistently than [mission-center v0.6.2](https://search.nixos.org/packages?channel=unstable&show=mission-center&from=0&size=50&sort=relevance&type=packages)
- Tested on both Ghaf and FMO target, X1 gen 11
Screenshots (taken from [upstream](https://github.com/nokyan/resources)):
Resources app will not launch via nwg-drawer until Ghaf dependency is updated to include changes from https://github.com/tiiuae/ghaf/pull/1190
Until then, this PR will remain in draft. Resources can be launched manually in guivm terminal with command `resources`.
1. TBD

feat: add resources app

---

flake.lock

Update onboarding-agent to release candidate version `1.0.0-rc.1`.
1. Flash the image and proceed with normal installation

bump: latest onboarding-agent

---

flake.lock

The latest givc will allow ease of profile switches.
1. ...

bump: get the latest givc changes.

---

flake.lock

Change device ID generation to use the older registration-agent version, due to NATS configuration and ROS parsing device IDs starting with a number as numbers and not strings.
- [SSRCDP-11049](https://jira.tii.ae/browse/SSRCDP-11049)
1. Reinstall as usual. Check if the bug [SSRCDP-11049](https://jira.tii.ae/browse/SSRCDP-11049) still persists. Ask from @solita-ilkkas for help.

fix(onboarding): device ID generation

---

flake.lock

Bump onboarding-agent to version [1.0.0-rc.3](https://github.com/tiiuae/onboarding-agent/releases/tag/v1.0.0-rc.3).
CHANGELOG: https://github.com/tiiuae/onboarding-agent/blob/main/CHANGELOG.md#100-rc3---2025-05-16
- [SECO-12258](https://jira.tii.ae/browse/SECO-12258)
1. When onboarding-agent starts, check that the version is logged (will be in the first lines)
2. If onboarding-agent fails, it should exit with `exit code 1` (previously was exiting with `exit code 0`, see the linked ticket)

bump(onboarding-agent): version 1.0.0-rc.3

---

flake.lock
flake.nix

Usual version bump with latest package updates.
1. ...

bump: Update to the latest ghaf and nixpkgs

---

modules/profile/fmo.nix

Adds code to enable ghaf default logging, disabled by default.
Once FMO grafana logging backend and functionality is determined, this can be enabled.
Tested on alienware, ID: 40-a1-d6-b2-4e-99
1. Enable logging, check logging ID (control-center), and verify on Grafana that device logs are available

feat(logging): enable logging

---

flake.lock

* Swapped identity CA and certificate in resulting laptop docker compose file
1. Needs re provisioning to write the correct docker compose file values

bump(onboarding-agent): version 1.0.0-rc.5

---

targets/flake-module.nix
targets/mkLaptopConfiguration.nix

The changes from ghaf, that were introduced when support was added for dm-verity based images, were not propogated downstream to fmo. so this addresses that.
1. ...

fix: Installer was broken by latest ghaf changes

---

modules/microvm/docker/config.nix

add: plugdev user to the dockervm

---

flake.lock

Simply bump onboarding-agent from version `1.0.0-rc.5` to `1.0.0` (no changes).
1. Usual onboarding process

bump(onboarding-agent): version 1.0.0

---

flake.nix

substitutor: Remove old deprecated substitutors

---

flake.lock
flake.nix

- Aligns to the version that ghaf is currently pinned to. 
- Includes a bump fix for cosmic cross compile.
- Fixes build error when using latest `ghaf`
1. Did a basic sanity test for the app openings, and everything appears to be working fine.

bump: latest nixpkgs and ghaf

---

flake.lock
modules/hardware/definition/dell-latitude-7230.nix
modules/hardware/usb/external-usb.nix
modules/microvm/docker/config.nix
modules/profile/fmo.nix

Align usb passthrough with updated Ghaf configs
1. Test all USB devices

bump Ghaf and nixpkgs

---

modules/fmo/fmo-docker-networking/default.nix
modules/profile/fmo.nix

Fix http internal docker-vm website availability, and enable ghaf power management in profile.
Note: Need to clarify exact ports that need to be opened and forwarded for the docker-vm. Current set is based on
docker containers and respective services running.
1. ...

Network and power updates

---

flake.lock
flake.nix
modules/profile/fmo.nix

bump: prepare for 1.4 based release

---

.github/workflows/check.yml

keys: Add private repo keys to GHA
